#! /bin/bash
#
# Executable virtual interpreter that may be used in the shebang line to execute Java source files by the kernel's program loader.
# 
# Globals:
#
# Options:
#
# Arguments:
# 
# Outputs:
#
# Returns:
# 
# https://shekhargulati.com/2020/10/26/writing-scripts-in-java-11-and-beyond/
# https://gist.github.com/posener/73ffd326d88483df6b1cb66e8ed1e0bd
# javavi stands for "java virtual interpreter"
#######################################