#! /bin/bash
# 
# An executable Bash script that creates or appends to all startup and shutdown files for Bash.
# Partial failure is allowed.
#
# Globals:
#   RC_FILES
# Options:
#   None
# Arguments:
#   File pathnames from which content will be supplied to chosen by options rc files
# Outputs:
#   Appends to startup and shutdown files. If files doesn't exist new files are created
#   Streams log data to stdout
# Returns:
#   0 if operation succeed, non-zero otherwise
#######################################

# shellcheck source=/Users/tomersha/Desktop/Tomer/cs/projects/shellf/src/main/lib/log4bash.sh
source /Users/tomersha/Desktop/Tomer/cs/projects/shellf/src/main/lib/log4bash.sh

readonly RC_FILES=("${HOME}/.bash_profile" "/etc/profile" "${HOME}/.bashrc" "${HOME}/.profile" "${HOME}/.bash_login" "${HOME}/.bash_logout")

main() {
  log4bash::warn "Partial failure is allowed"

  if [ "$#" -lt 1 ]; then
    log4bash::err "Missing arguments."
    exit 1
  fi
  
  for v in "$@"; do
    if [[ -f "${v}" ]]; then
        for rc_file in "${RC_FILES[@]}"; do
          cat "${v}" >> "${rc_file}"
          log4bash::log "Appended '${v}' to '${rc_file}'"
        done
    else
      log4bash::err "No such file: '${v}'"
    fi
  done 
}

main "$@"
